import type { Metadata } from 'next'
import { JetBrains_Mono, Merriweather, Outfit } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import { Toaster } from 'sonner'

const fontSans = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit-sans',
  weight: ['400', '500', '600', '700'],
})

const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
  weight: ['400', '500', '600', '700'],
})

const fontSerif = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather-serif',
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: ['nextjs', 'typescript', 'tailwindcss'],
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
  },
  openGraph: {
    type: 'website',
    url: 'https://nextjs.org',
    title: 'Create Next App',
    description: 'Generated by create next app',

    images: [
      {
        url: 'https://nextjs.org/og-image.png',
        width: 800,
        height: 600,
        alt: 'Create Next App logo',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Create Next App',
    description: 'Generated by create next app',
    images: [
      {
        url: 'https://nextjs.org/og-image.png',
        width: 800,
        height: 600,
        alt: 'Create Next App logo',
      },
    ],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} ${fontSerif.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  )
}
